version: "3"
services:
  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqlvol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    command: ash -c "rm -rf tmp/pids/server.pid; bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - ./backend:/app/backend
      - bundle:/usr/local/bundle
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_HOST=db
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

  frontend:
    build: ./frontend
    command: yarn serve
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
    tty: true
volumes:
  mysqlvol:
  bundle:
  node-modules:
